import type { InsertFormation } from "@workspace/db";
import type { InsertSuggestedPlay } from "@workspace/db";

export const SEED_FORMATIONS: InsertFormation[] = [
  // 5v5 Offense
  {
    id: "form-5v5-spread",
    name: "Spread",
    format: "5v5",
    mode: "offense",
    description: "4 wide receivers spread across the field with QB under center",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "WR1", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "WR2", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "WR3", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "WR4", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
  },
  {
    id: "form-5v5-trips",
    name: "Trips Right",
    format: "5v5",
    mode: "offense",
    description: "Three receivers bunched to the right, one isolated left",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "WR1", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "WR2", x: 65, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "WR3", x: 78, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "WR4", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
  },
  {
    id: "form-5v5-ace",
    name: "Ace",
    format: "5v5",
    mode: "offense",
    description: "Balanced formation with RB in backfield",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "RB", label: "RB", x: 50, y: 52, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR1", label: "WR1", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR2", label: "WR2", x: 30, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR3", label: "WR3", x: 80, y: 55, color: "#22c55e", team: "offense" },
    ],
  },
  // 5v5 Defense
  {
    id: "form-5v5-man",
    name: "Man Coverage",
    format: "5v5",
    mode: "defense",
    description: "One-on-one man coverage with single rusher",
    players: [
      { id: "p1", role: "Rusher", label: "RUSH", x: 50, y: 40, color: "#ef4444", team: "defense" },
      { id: "p2", role: "DB", label: "DB1", x: 15, y: 40, color: "#ef4444", team: "defense" },
      { id: "p3", role: "DB", label: "DB2", x: 30, y: 40, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "DB3", x: 70, y: 40, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "DB4", x: 85, y: 40, color: "#ef4444", team: "defense" },
    ],
  },
  // 7v7 Offense
  {
    id: "form-7v7-pro",
    name: "Pro Set",
    format: "7v7",
    mode: "offense",
    description: "Traditional pro formation with center, two TEs, two WRs, RB",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "WR1", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "WR2", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "WR3", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "WR4", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
  },
  {
    id: "form-7v7-trips-te",
    name: "Trips TE",
    format: "7v7",
    mode: "offense",
    description: "Three receiver trips with TE inline, RB in backfield",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 42, y: 52, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "WR1", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "TE", label: "TE", x: 62, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR2", label: "WR2", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR3", label: "WR3", x: 88, y: 55, color: "#22c55e", team: "offense" },
    ],
  },
  // 7v7 Defense
  {
    id: "form-7v7-cover2",
    name: "Cover 2",
    format: "7v7",
    mode: "defense",
    description: "Zone with two deep safeties, four underneath defenders",
    players: [
      { id: "p1", role: "Safety", label: "FS", x: 30, y: 30, color: "#ef4444", team: "defense" },
      { id: "p2", role: "Safety", label: "SS", x: 70, y: 30, color: "#ef4444", team: "defense" },
      { id: "p3", role: "Rusher", label: "RUSH", x: 50, y: 40, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB1", x: 10, y: 40, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB2", x: 90, y: 40, color: "#ef4444", team: "defense" },
      { id: "p6", role: "LB", label: "LB1", x: 35, y: 40, color: "#ef4444", team: "defense" },
      { id: "p7", role: "LB", label: "LB2", x: 65, y: 40, color: "#ef4444", team: "defense" },
    ],
  },
  {
    id: "form-7v7-blitz",
    name: "All Out Blitz",
    format: "7v7",
    mode: "defense",
    description: "Multiple rushers with aggressive man coverage",
    players: [
      { id: "p1", role: "Safety", label: "FS", x: 50, y: 28, color: "#ef4444", team: "defense" },
      { id: "p2", role: "Rusher", label: "R1", x: 42, y: 40, color: "#ef4444", team: "defense" },
      { id: "p3", role: "Rusher", label: "R2", x: 58, y: 40, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB1", x: 10, y: 40, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB2", x: 25, y: 40, color: "#ef4444", team: "defense" },
      { id: "p6", role: "DB", label: "CB3", x: 75, y: 40, color: "#ef4444", team: "defense" },
      { id: "p7", role: "DB", label: "CB4", x: 90, y: 40, color: "#ef4444", team: "defense" },
    ],
  },
];

export const SEED_PLAYBOOKS = [
  {
    id: "pb-red-zone",
    name: "Red Zone Package",
    description: "Short yardage and red zone plays",
    format: "5v5",
    color: "#ef4444",
    playCount: 0,
  },
  {
    id: "pb-base-offense",
    name: "Base Offense",
    description: "Core offensive play set for 5v5",
    format: "5v5",
    color: "#22c55e",
    playCount: 0,
  },
  {
    id: "pb-7v7-offense",
    name: "7v7 Offensive Playbook",
    description: "Full 7v7 offensive scheme",
    format: "7v7",
    color: "#3b82f6",
    playCount: 0,
  },
];

export const SEED_SUGGESTED_PLAYS: InsertSuggestedPlay[] = [
  // ── 5v5 Offense ──────────────────────────────────────────────────────────
  {
    id: "sp-hitch-flood",
    name: "Hitch & Flood",
    coachingPurpose: "Quick hitch to X receiver with flood concept to stress zone coverage",
    idealSituation: "Short yardage, zone coverage, midfield",
    format: "5v5",
    mode: "offense",
    tags: ["quick", "zone-beater", "hitch"],
    coverageAttacked: "zone",
    primaryConcept: "hitch",
    difficulty: "beginner",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "hitch", points: [{ x: 10, y: 55 }, { x: 10, y: 45 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "out", points: [{ x: 25, y: 55 }, { x: 25, y: 45 }, { x: 10, y: 42 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "post", points: [{ x: 75, y: 55 }, { x: 75, y: 40 }, { x: 60, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "go", points: [{ x: 90, y: 55 }, { x: 90, y: 30 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-slant-bubble",
    name: "Slant & Bubble",
    coachingPurpose: "Slant to backside with bubble screen to the field side — attacks man and zone",
    idealSituation: "Any situation, quick release needed",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "zone-beater", "slant", "screen"],
    coverageAttacked: "man, zone",
    primaryConcept: "slant",
    difficulty: "beginner",
    fieldZone: "any",
    isManBeater: true,
    isZoneBeater: true,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "slant", points: [{ x: 10, y: 55 }, { x: 10, y: 48 }, { x: 30, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "drag", points: [{ x: 25, y: 55 }, { x: 25, y: 48 }, { x: 50, y: 44 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "screen", points: [{ x: 75, y: 55 }, { x: 65, y: 53 }], style: "dotted", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "go", points: [{ x: 90, y: 55 }, { x: 90, y: 30 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-corner-post",
    name: "Corner-Post",
    coachingPurpose: "High-low concept with a corner route over the top and a post underneath",
    idealSituation: "2nd and medium, cover 2 shell",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "corner", "post"],
    coverageAttacked: "cover-2",
    primaryConcept: "corner-post",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-trips",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 65, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 78, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "post", points: [{ x: 15, y: 55 }, { x: 15, y: 42 }, { x: 35, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "drag", points: [{ x: 65, y: 55 }, { x: 65, y: 48 }, { x: 40, y: 44 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "corner", points: [{ x: 78, y: 55 }, { x: 78, y: 42 }, { x: 92, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-stop-go",
    name: "Stop and Go",
    coachingPurpose: "Double move — hitch then release deep to beat press man",
    idealSituation: "Press man coverage, big play situation",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "double-move"],
    coverageAttacked: "man",
    primaryConcept: "double-move",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "comeback", points: [{ x: 10, y: 55 }, { x: 10, y: 42 }, { x: 10, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "out", points: [{ x: 25, y: 55 }, { x: 25, y: 44 }, { x: 10, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "in", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 55, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "go", points: [{ x: 90, y: 55 }, { x: 90, y: 28 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-shallow-cross",
    name: "Shallow Cross",
    coachingPurpose: "High-speed shallow route crossing the field to stress zone windows",
    idealSituation: "Zone coverage, 2nd and medium",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "crossing", "drag"],
    coverageAttacked: "zone",
    primaryConcept: "crossing",
    difficulty: "beginner",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "drag", points: [{ x: 10, y: 55 }, { x: 10, y: 50 }, { x: 80, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "out", points: [{ x: 25, y: 55 }, { x: 25, y: 44 }, { x: 10, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "post", points: [{ x: 75, y: 55 }, { x: 75, y: 40 }, { x: 55, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-trips-flood",
    name: "Trips Flood",
    coachingPurpose: "Three receivers flood one side to overwhelm zone or create spacing vs man",
    idealSituation: "Red zone, any coverage",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "man-beater", "trips", "flood", "red-zone"],
    coverageAttacked: "zone, man",
    primaryConcept: "flood",
    difficulty: "beginner",
    fieldZone: "red_zone",
    isManBeater: true,
    isZoneBeater: true,
    formationId: "form-5v5-trips",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 65, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 78, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "post", points: [{ x: 15, y: 55 }, { x: 15, y: 40 }, { x: 35, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "go", points: [{ x: 65, y: 55 }, { x: 65, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "out", points: [{ x: 78, y: 55 }, { x: 78, y: 44 }, { x: 92, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 48 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-four-verts",
    name: "Four Verticals",
    coachingPurpose: "Stretch coverage deep with 4 vertical routes, attack seams in cover 2",
    idealSituation: "Long yardage, soft zone",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "deep", "vertical"],
    coverageAttacked: "cover-2",
    primaryConcept: "vertical",
    difficulty: "beginner",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 30, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 70, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "go", points: [{ x: 10, y: 55 }, { x: 10, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "go", points: [{ x: 30, y: 55 }, { x: 30, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "go", points: [{ x: 70, y: 55 }, { x: 70, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "go", points: [{ x: 90, y: 55 }, { x: 90, y: 28 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-wheel-seam",
    name: "Wheel & Seam",
    coachingPurpose: "RB wheel route pairs with WR seam to stress two-high coverage",
    idealSituation: "Cover 2, red zone",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "wheel", "seam", "red-zone"],
    coverageAttacked: "cover-2",
    primaryConcept: "wheel",
    difficulty: "intermediate",
    fieldZone: "red_zone",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-ace",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "RB", label: "RB", x: 50, y: 52, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR1", label: "X", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR2", label: "H", x: 30, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR3", label: "Z", x: 80, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "wheel", points: [{ x: 50, y: 52 }, { x: 62, y: 52 }, { x: 75, y: 44 }, { x: 75, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "go", points: [{ x: 15, y: 55 }, { x: 15, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "post", points: [{ x: 30, y: 55 }, { x: 30, y: 42 }, { x: 48, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 80, y: 55 }, { x: 80, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-motion-iso",
    name: "Motion Iso",
    coachingPurpose: "Pre-snap motion isolates fastest receiver on one-on-one",
    idealSituation: "Man coverage, open field",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "motion", "isolation"],
    coverageAttacked: "man",
    primaryConcept: "isolation",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r0", playerId: "p3", type: "motion", points: [{ x: 25, y: 55 }, { x: 85, y: 55 }], style: "dashed", color: "#f59e0b" },
      { id: "r1", playerId: "p2", type: "slant", points: [{ x: 10, y: 55 }, { x: 10, y: 48 }, { x: 28, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "go", points: [{ x: 85, y: 55 }, { x: 85, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "in", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 55, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "out", points: [{ x: 90, y: 55 }, { x: 90, y: 44 }, { x: 95, y: 40 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-chair",
    name: "Chair Route",
    coachingPurpose: "Double-cut chair pattern fakes inside then breaks back out",
    idealSituation: "Man coverage, tight coverage corners",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "chair", "double-cut"],
    coverageAttacked: "man",
    primaryConcept: "chair",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "out", points: [{ x: 10, y: 55 }, { x: 10, y: 48 }, { x: 25, y: 44 }, { x: 10, y: 38 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "post", points: [{ x: 25, y: 55 }, { x: 25, y: 40 }, { x: 42, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "corner", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 88, y: 34 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "drag", points: [{ x: 90, y: 55 }, { x: 90, y: 49 }, { x: 60, y: 46 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-post-corner-iso",
    name: "Post-Corner",
    coachingPurpose: "Deep double-move post then break corner — beats single safety coverage",
    idealSituation: "Cover 1, single high safety",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "post-corner", "deep"],
    coverageAttacked: "cover-1",
    primaryConcept: "post-corner",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "corner", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 62, y: 34 }, { x: 88, y: 24 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p2", type: "post", points: [{ x: 10, y: 55 }, { x: 10, y: 40 }, { x: 30, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p3", type: "hitch", points: [{ x: 25, y: 55 }, { x: 25, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "out", points: [{ x: 90, y: 55 }, { x: 90, y: 44 }, { x: 96, y: 40 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-option-route",
    name: "Option Route",
    coachingPurpose: "Receiver reads coverage and breaks inside or outside based on leverage",
    idealSituation: "Man coverage with experienced receiver",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "option", "read"],
    coverageAttacked: "man",
    primaryConcept: "option",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "out", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 88, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p2", type: "post", points: [{ x: 10, y: 55 }, { x: 10, y: 40 }, { x: 28, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p3", type: "slant", points: [{ x: 25, y: 55 }, { x: 25, y: 48 }, { x: 42, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  // Red zone plays
  {
    id: "sp-redzone-fade",
    name: "Back-Shoulder Fade",
    coachingPurpose: "Back-shoulder throw to sideline in red zone vs press man",
    idealSituation: "Red zone, goal line, press man coverage",
    format: "5v5",
    mode: "offense",
    tags: ["man-beater", "fade", "red-zone"],
    coverageAttacked: "man",
    primaryConcept: "fade",
    difficulty: "intermediate",
    fieldZone: "red_zone",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "go", points: [{ x: 10, y: 55 }, { x: 8, y: 35 }, { x: 5, y: 25 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "out", points: [{ x: 25, y: 55 }, { x: 25, y: 44 }, { x: 10, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "in", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 58, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-rz-out-cut",
    name: "Red Zone Out Cut",
    coachingPurpose: "Sharp out cut to sideline in compressed red zone space",
    idealSituation: "Red zone, any coverage",
    format: "5v5",
    mode: "offense",
    tags: ["zone-beater", "out", "red-zone", "short-yardage"],
    coverageAttacked: "zone",
    primaryConcept: "out",
    difficulty: "beginner",
    fieldZone: "red_zone",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-trips",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 15, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 65, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 78, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "corner", points: [{ x: 15, y: 55 }, { x: 15, y: 44 }, { x: 5, y: 34 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "out", points: [{ x: 65, y: 55 }, { x: 65, y: 46 }, { x: 78, y: 42 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "out", points: [{ x: 78, y: 55 }, { x: 78, y: 44 }, { x: 94, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
    ],
  },
  // Backed up plays
  {
    id: "sp-backed-quick-out",
    name: "Quick Outs",
    coachingPurpose: "Fast-hitting out routes to get yardage when backed up",
    idealSituation: "Backed up in own end zone, quick gain needed",
    format: "5v5",
    mode: "offense",
    tags: ["quick", "backed-up", "out"],
    coverageAttacked: "zone",
    primaryConcept: "quick-game",
    difficulty: "beginner",
    fieldZone: "backed_up",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-5v5-spread",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "out", points: [{ x: 10, y: 55 }, { x: 10, y: 48 }, { x: 2, y: 45 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p3", type: "hitch", points: [{ x: 25, y: 55 }, { x: 25, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "hitch", points: [{ x: 75, y: 55 }, { x: 75, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "out", points: [{ x: 90, y: 55 }, { x: 90, y: 48 }, { x: 98, y: 45 }], style: "solid", color: "#22c55e" },
    ],
  },
  // ── 7v7 Offense ──────────────────────────────────────────────────────────
  {
    id: "sp-7v7-mesh",
    name: "Mesh Concept",
    coachingPurpose: "Two crossing routes at 6 yards — rubs defenders and creates easy completions",
    idealSituation: "Man coverage, any field position",
    format: "7v7",
    mode: "offense",
    tags: ["man-beater", "crossing", "mesh"],
    coverageAttacked: "man",
    primaryConcept: "mesh",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "drag", points: [{ x: 10, y: 55 }, { x: 10, y: 49 }, { x: 80, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p7", type: "drag", points: [{ x: 90, y: 55 }, { x: 90, y: 49 }, { x: 20, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p5", type: "post", points: [{ x: 25, y: 55 }, { x: 25, y: 40 }, { x: 45, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p6", type: "corner", points: [{ x: 75, y: 55 }, { x: 75, y: 42 }, { x: 88, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "screen", points: [{ x: 50, y: 50 }, { x: 38, y: 50 }], style: "dotted", color: "#22c55e" },
    ],
  },
  {
    id: "sp-7v7-triangle",
    name: "Triangle Flood",
    coachingPurpose: "Three-level flood on one side — high/mid/low read for QB",
    idealSituation: "Zone coverage, any field position",
    format: "7v7",
    mode: "offense",
    tags: ["zone-beater", "flood", "triangle"],
    coverageAttacked: "zone",
    primaryConcept: "flood",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-7v7-trips-te",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 42, y: 52, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "TE", label: "TE", x: 62, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR2", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR3", label: "W", x: 88, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "post", points: [{ x: 10, y: 55 }, { x: 10, y: 38 }, { x: 32, y: 26 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "drag", points: [{ x: 62, y: 55 }, { x: 62, y: 49 }, { x: 25, y: 46 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "go", points: [{ x: 75, y: 55 }, { x: 75, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "out", points: [{ x: 88, y: 55 }, { x: 88, y: 44 }, { x: 98, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "screen", points: [{ x: 42, y: 52 }, { x: 32, y: 52 }], style: "dotted", color: "#22c55e" },
    ],
  },
  {
    id: "sp-7v7-smash",
    name: "Smash",
    coachingPurpose: "Corner-hitch combo attacks cover 2 — low route to CB, high corner over",
    idealSituation: "Cover 2 / cover 4 shell",
    format: "7v7",
    mode: "offense",
    tags: ["zone-beater", "smash", "corner", "hitch"],
    coverageAttacked: "cover-2",
    primaryConcept: "smash",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "hitch", points: [{ x: 10, y: 55 }, { x: 10, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "corner", points: [{ x: 25, y: 55 }, { x: 25, y: 42 }, { x: 10, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "hitch", points: [{ x: 75, y: 55 }, { x: 75, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "corner", points: [{ x: 90, y: 55 }, { x: 90, y: 42 }, { x: 96, y: 30 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "in", points: [{ x: 50, y: 50 }, { x: 50, y: 44 }, { x: 34, y: 40 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-7v7-levels",
    name: "Levels",
    coachingPurpose: "Three receivers at different depths on one side — stacks zone defenders",
    idealSituation: "Zone coverage, mid-field",
    format: "7v7",
    mode: "offense",
    tags: ["zone-beater", "levels"],
    coverageAttacked: "zone",
    primaryConcept: "levels",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 22, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "go", points: [{ x: 10, y: 55 }, { x: 10, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "in", points: [{ x: 22, y: 55 }, { x: 22, y: 44 }, { x: 48, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "drag", points: [{ x: 75, y: 55 }, { x: 75, y: 50 }, { x: 40, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "corner", points: [{ x: 90, y: 55 }, { x: 90, y: 40 }, { x: 98, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "screen", points: [{ x: 50, y: 50 }, { x: 40, y: 50 }], style: "dotted", color: "#22c55e" },
    ],
  },
  {
    id: "sp-7v7-halfback-pass",
    name: "HB Pass",
    coachingPurpose: "Halfback throwback catch-and-throw gadget — attacks aggressive rushers",
    idealSituation: "Blitz-heavy defense, run-and-shoot tendency",
    format: "7v7",
    mode: "offense",
    tags: ["gadget", "motion", "blitz-beater"],
    coverageAttacked: "blitz",
    primaryConcept: "gadget",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 42, y: 52, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r0", playerId: "p1", type: "handoff", points: [{ x: 50, y: 60 }, { x: 42, y: 52 }], style: "dotted", color: "#f59e0b" },
      { id: "r1", playerId: "p4", type: "go", points: [{ x: 10, y: 55 }, { x: 10, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "post", points: [{ x: 25, y: 55 }, { x: 25, y: 40 }, { x: 42, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "go", points: [{ x: 75, y: 55 }, { x: 75, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "out", points: [{ x: 90, y: 55 }, { x: 90, y: 44 }, { x: 98, y: 40 }], style: "solid", color: "#22c55e" },
    ],
  },
  {
    id: "sp-7v7-rpo-bubble",
    name: "RPO Bubble",
    coachingPurpose: "Run-pass option with bubble to field side based on CB alignment",
    idealSituation: "Any down, cover 1 or man",
    format: "7v7",
    mode: "offense",
    tags: ["man-beater", "RPO", "bubble", "screen"],
    coverageAttacked: "man",
    primaryConcept: "RPO",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: false,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p7", type: "screen", points: [{ x: 90, y: 55 }, { x: 80, y: 53 }], style: "dotted", color: "#22c55e" },
      { id: "r2", playerId: "p6", type: "go", points: [{ x: 75, y: 55 }, { x: 75, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p4", type: "slant", points: [{ x: 10, y: 55 }, { x: 10, y: 48 }, { x: 28, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p5", type: "drag", points: [{ x: 25, y: 55 }, { x: 25, y: 49 }, { x: 55, y: 46 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "handoff", points: [{ x: 50, y: 50 }, { x: 52, y: 50 }], style: "dotted", color: "#f59e0b" },
    ],
  },
  // ── Defense ──────────────────────────────────────────────────────────────
  {
    id: "sp-def-man-press",
    name: "Press Man",
    coachingPurpose: "Aggressive press man with single rusher — limits routes at line",
    idealSituation: "Short yardage, red zone, vs inexperienced receivers",
    format: "5v5",
    mode: "defense",
    tags: ["man", "press", "blitz"],
    coverageAttacked: "",
    primaryConcept: "man",
    difficulty: "intermediate",
    fieldZone: "red_zone",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-5v5-man",
    players: [
      { id: "p1", role: "Rusher", label: "RUSH", x: 50, y: 40, color: "#ef4444", team: "defense" },
      { id: "p2", role: "DB", label: "CB1", x: 10, y: 51, color: "#ef4444", team: "defense" },
      { id: "p3", role: "DB", label: "CB2", x: 25, y: 51, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB3", x: 75, y: 51, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB4", x: 90, y: 51, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "zone_drop", points: [{ x: 10, y: 51 }, { x: 10, y: 40 }], style: "dashed", color: "#ef4444" },
      { id: "r2", playerId: "p3", type: "zone_drop", points: [{ x: 25, y: 51 }, { x: 25, y: 40 }], style: "dashed", color: "#ef4444" },
      { id: "r3", playerId: "p4", type: "zone_drop", points: [{ x: 75, y: 51 }, { x: 75, y: 40 }], style: "dashed", color: "#ef4444" },
      { id: "r4", playerId: "p5", type: "zone_drop", points: [{ x: 90, y: 51 }, { x: 90, y: 40 }], style: "dashed", color: "#ef4444" },
    ],
  },
  {
    id: "sp-def-cover2-zone",
    name: "Cover 2 Zone",
    coachingPurpose: "Two deep halves zone with three underneath — limits explosive plays",
    idealSituation: "Long yardage, protect against deep shots",
    format: "7v7",
    mode: "defense",
    tags: ["zone", "cover-2", "prevent"],
    coverageAttacked: "",
    primaryConcept: "zone",
    difficulty: "beginner",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-7v7-cover2",
    players: [
      { id: "p1", role: "Safety", label: "FS", x: 30, y: 30, color: "#ef4444", team: "defense" },
      { id: "p2", role: "Safety", label: "SS", x: 70, y: 30, color: "#ef4444", team: "defense" },
      { id: "p3", role: "Rusher", label: "RUSH", x: 50, y: 43, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB1", x: 10, y: 43, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB2", x: 90, y: 43, color: "#ef4444", team: "defense" },
      { id: "p6", role: "LB", label: "LB1", x: 35, y: 43, color: "#ef4444", team: "defense" },
      { id: "p7", role: "LB", label: "LB2", x: 65, y: 43, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p1", type: "zone_drop", points: [{ x: 30, y: 30 }, { x: 15, y: 25 }], style: "dashed", color: "#ef4444" },
      { id: "r2", playerId: "p2", type: "zone_drop", points: [{ x: 70, y: 30 }, { x: 85, y: 25 }], style: "dashed", color: "#ef4444" },
      { id: "r3", playerId: "p4", type: "zone_drop", points: [{ x: 10, y: 43 }, { x: 10, y: 38 }], style: "dashed", color: "#ef4444" },
      { id: "r4", playerId: "p5", type: "zone_drop", points: [{ x: 90, y: 43 }, { x: 90, y: 38 }], style: "dashed", color: "#ef4444" },
      { id: "r5", playerId: "p6", type: "zone_drop", points: [{ x: 35, y: 43 }, { x: 35, y: 38 }], style: "dashed", color: "#ef4444" },
      { id: "r6", playerId: "p7", type: "zone_drop", points: [{ x: 65, y: 43 }, { x: 65, y: 38 }], style: "dashed", color: "#ef4444" },
    ],
  },
  {
    id: "sp-def-all-out-blitz",
    name: "All Out Blitz",
    coachingPurpose: "Send all available rushers and play 1-on-1 man — pressure package",
    idealSituation: "3rd and long, must stop play",
    format: "7v7",
    mode: "defense",
    tags: ["blitz", "man", "pressure"],
    coverageAttacked: "",
    primaryConcept: "blitz",
    difficulty: "advanced",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-7v7-blitz",
    players: [
      { id: "p1", role: "Safety", label: "FS", x: 50, y: 28, color: "#ef4444", team: "defense" },
      { id: "p2", role: "Rusher", label: "R1", x: 42, y: 40, color: "#ef4444", team: "defense" },
      { id: "p3", role: "Rusher", label: "R2", x: 58, y: 40, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB1", x: 10, y: 43, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB2", x: 25, y: 43, color: "#ef4444", team: "defense" },
      { id: "p6", role: "DB", label: "CB3", x: 75, y: 43, color: "#ef4444", team: "defense" },
      { id: "p7", role: "DB", label: "CB4", x: 90, y: 43, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p2", type: "straight", points: [{ x: 42, y: 40 }, { x: 50, y: 58 }], style: "solid", color: "#ef4444" },
      { id: "r2", playerId: "p3", type: "straight", points: [{ x: 58, y: 40 }, { x: 50, y: 58 }], style: "solid", color: "#ef4444" },
      { id: "r3", playerId: "p4", type: "zone_drop", points: [{ x: 10, y: 43 }, { x: 10, y: 38 }], style: "dashed", color: "#ef4444" },
      { id: "r4", playerId: "p5", type: "zone_drop", points: [{ x: 25, y: 43 }, { x: 25, y: 38 }], style: "dashed", color: "#ef4444" },
    ],
  },
  {
    id: "sp-def-cover3",
    name: "Cover 3 Zone",
    coachingPurpose: "Three-deep zone — limits vertical plays, defenders rotate to cover seams",
    idealSituation: "Long yardage, opponent has fast WRs",
    format: "7v7",
    mode: "defense",
    tags: ["zone", "cover-3", "deep"],
    coverageAttacked: "",
    primaryConcept: "zone",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-7v7-cover2",
    players: [
      { id: "p1", role: "Safety", label: "FS", x: 50, y: 25, color: "#ef4444", team: "defense" },
      { id: "p2", role: "DB", label: "CB1", x: 10, y: 30, color: "#ef4444", team: "defense" },
      { id: "p3", role: "DB", label: "CB2", x: 90, y: 30, color: "#ef4444", team: "defense" },
      { id: "p4", role: "Rusher", label: "RUSH", x: 50, y: 43, color: "#ef4444", team: "defense" },
      { id: "p5", role: "LB", label: "LB1", x: 28, y: 43, color: "#ef4444", team: "defense" },
      { id: "p6", role: "LB", label: "LB2", x: 50, y: 40, color: "#ef4444", team: "defense" },
      { id: "p7", role: "LB", label: "LB3", x: 72, y: 43, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p1", type: "zone_drop", points: [{ x: 50, y: 25 }, { x: 50, y: 20 }], style: "dashed", color: "#ef4444" },
      { id: "r2", playerId: "p2", type: "zone_drop", points: [{ x: 10, y: 30 }, { x: 5, y: 25 }], style: "dashed", color: "#ef4444" },
      { id: "r3", playerId: "p3", type: "zone_drop", points: [{ x: 90, y: 30 }, { x: 95, y: 25 }], style: "dashed", color: "#ef4444" },
      { id: "r4", playerId: "p5", type: "zone_drop", points: [{ x: 28, y: 43 }, { x: 28, y: 37 }], style: "dashed", color: "#ef4444" },
      { id: "r5", playerId: "p7", type: "zone_drop", points: [{ x: 72, y: 43 }, { x: 72, y: 37 }], style: "dashed", color: "#ef4444" },
    ],
  },
  {
    id: "sp-def-spy",
    name: "QB Spy",
    coachingPurpose: "Assign a defender to spy the QB — counters scrambling QBs",
    idealSituation: "Mobile QB, broken plays",
    format: "5v5",
    mode: "defense",
    tags: ["man", "spy", "QB-contain"],
    coverageAttacked: "",
    primaryConcept: "spy",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-5v5-man",
    players: [
      { id: "p1", role: "Rusher", label: "RUSH", x: 50, y: 42, color: "#ef4444", team: "defense" },
      { id: "p2", role: "DB", label: "CB1", x: 10, y: 43, color: "#ef4444", team: "defense" },
      { id: "p3", role: "DB", label: "CB2", x: 25, y: 43, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "SPY", x: 50, y: 50, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB4", x: 90, y: 43, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "zone_drop", points: [{ x: 50, y: 50 }, { x: 50, y: 44 }], style: "dashed", color: "#ef4444" },
    ],
  },
  {
    id: "sp-def-cover0-rz",
    name: "Cover 0 Red Zone",
    coachingPurpose: "Pure man with all defenders — gamble in red zone for big stop",
    idealSituation: "Red zone goal line, must stop",
    format: "5v5",
    mode: "defense",
    tags: ["man", "blitz", "cover-0", "red-zone"],
    coverageAttacked: "",
    primaryConcept: "cover-0",
    difficulty: "advanced",
    fieldZone: "red_zone",
    isManBeater: false,
    isZoneBeater: false,
    formationId: "form-5v5-man",
    players: [
      { id: "p1", role: "Rusher", label: "RUSH", x: 50, y: 40, color: "#ef4444", team: "defense" },
      { id: "p2", role: "DB", label: "CB1", x: 10, y: 51, color: "#ef4444", team: "defense" },
      { id: "p3", role: "DB", label: "CB2", x: 25, y: 51, color: "#ef4444", team: "defense" },
      { id: "p4", role: "DB", label: "CB3", x: 75, y: 51, color: "#ef4444", team: "defense" },
      { id: "p5", role: "DB", label: "CB4", x: 90, y: 51, color: "#ef4444", team: "defense" },
    ],
    routes: [
      { id: "r1", playerId: "p1", type: "straight", points: [{ x: 50, y: 40 }, { x: 50, y: 58 }], style: "solid", color: "#ef4444" },
    ],
  },
  {
    id: "sp-7v7-trips-rz",
    name: "7v7 Trips Red Zone",
    coachingPurpose: "Overload one side of the end zone with three receivers",
    idealSituation: "Red zone, goal line",
    format: "7v7",
    mode: "offense",
    tags: ["zone-beater", "trips", "red-zone"],
    coverageAttacked: "zone",
    primaryConcept: "trips",
    difficulty: "intermediate",
    fieldZone: "red_zone",
    isManBeater: false,
    isZoneBeater: true,
    formationId: "form-7v7-trips-te",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 42, y: 52, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "TE", label: "TE", x: 62, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR2", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR3", label: "W", x: 88, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r1", playerId: "p4", type: "slant", points: [{ x: 10, y: 55 }, { x: 10, y: 46 }, { x: 28, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "out", points: [{ x: 62, y: 55 }, { x: 62, y: 44 }, { x: 76, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "corner", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 88, y: 32 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "go", points: [{ x: 88, y: 55 }, { x: 88, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "screen", points: [{ x: 42, y: 52 }, { x: 32, y: 52 }], style: "dotted", color: "#22c55e" },
    ],
  },
  {
    id: "sp-motion-trap",
    name: "Motion Trap",
    coachingPurpose: "Use pre-snap motion to identify man vs zone and attack accordingly",
    idealSituation: "Any down, any coverage — read and react",
    format: "7v7",
    mode: "offense",
    tags: ["man-beater", "zone-beater", "motion", "read"],
    coverageAttacked: "man, zone",
    primaryConcept: "motion",
    difficulty: "intermediate",
    fieldZone: "midfield",
    isManBeater: true,
    isZoneBeater: true,
    formationId: "form-7v7-pro",
    players: [
      { id: "p1", role: "QB", label: "QB", x: 50, y: 60, color: "#22c55e", team: "offense" },
      { id: "p2", role: "C", label: "C", x: 50, y: 55, color: "#22c55e", team: "offense" },
      { id: "p3", role: "RB", label: "RB", x: 50, y: 50, color: "#22c55e", team: "offense" },
      { id: "p4", role: "WR1", label: "X", x: 10, y: 55, color: "#22c55e", team: "offense" },
      { id: "p5", role: "WR2", label: "H", x: 25, y: 55, color: "#22c55e", team: "offense" },
      { id: "p6", role: "WR3", label: "Z", x: 75, y: 55, color: "#22c55e", team: "offense" },
      { id: "p7", role: "WR4", label: "W", x: 90, y: 55, color: "#22c55e", team: "offense" },
    ],
    routes: [
      { id: "r0", playerId: "p5", type: "motion", points: [{ x: 25, y: 55 }, { x: 78, y: 55 }], style: "dashed", color: "#f59e0b" },
      { id: "r1", playerId: "p4", type: "post", points: [{ x: 10, y: 55 }, { x: 10, y: 40 }, { x: 30, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r2", playerId: "p5", type: "go", points: [{ x: 78, y: 55 }, { x: 78, y: 28 }], style: "solid", color: "#22c55e" },
      { id: "r3", playerId: "p6", type: "in", points: [{ x: 75, y: 55 }, { x: 75, y: 44 }, { x: 55, y: 40 }], style: "solid", color: "#22c55e" },
      { id: "r4", playerId: "p7", type: "hitch", points: [{ x: 90, y: 55 }, { x: 90, y: 47 }], style: "solid", color: "#22c55e" },
      { id: "r5", playerId: "p3", type: "screen", points: [{ x: 50, y: 50 }, { x: 38, y: 50 }], style: "dotted", color: "#22c55e" },
    ],
  },
];
